image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - apk add bash make

stages:
  - infra
  - db

tf-apply:
  stage: infra
  script:
    - make tf:init
    - make tf:plan
    - make tf:apply

mkdb:
  stage: db
  script:
    - make dkr:build
    - docker run pgrunner:$(cat ./.project-version)
