image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - apk add bash make

stages:
  - apply

apply:
  stage: apply
  script:
    make tf:init
    make tf:plan
    make tf:apply
